name: Node.js CI

# Trigger which git action (push, pull_request)
# in which branch(es) should start the jobs...
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  # add branch-protection-rules in github for main (require pull-request)
  # then add another branch and try to make a pull-request in github
  # to merge your branch into main:
  # - the following will happens: these tests will run
  # - and a report of success/failure will be shown to the person
  #   approving the pull request

# jobs to run
jobs:
  # build, the name of the job, a server to create and auto configure
  build:

    runs-on: ubuntu-latest

    strategy:
      # only testing on Node 20 now but could have done
      # several builds by adding [16.x, 18.x] etc
      matrix:
        node-version: [20.x]

    steps:
      # action from github marketplace, actions
      # checkout this repo on the server
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      # action from github marketplace, actions
      # install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      # npm ci ≈ read-only from package.json version
      # of npm install -> installs all npm modules
      # mentioned in package.json, preferably during CI
    - run: npm ci
      # if the project has a npm run build command
      # then runs (not needed right now but keep)
    - run: npm run build --if-present
      # start the web server (without hanging the terminal)
      # note nohup does NOT work with the npm command,
      # so run using the node command instead
    - run: nohup node index.js &
      # run whatever is specified in package.json
      # for the script test
    - run: npm test
      # make sure to run with colored output
      env:
        FORCE_COLOR: 2
